### ISSUE TITLE
desisim/0.9.3 can't find ecsv files

### ISSUE THREAD

**Issue by weaverba137** [desihub/desisim#119]
When running the pipeline integration test with desisim/0.9.3, the test fails because desisim can't find data files it needs.  The problem is that `../../data/recombination_lines.ecsv` only works from a git clone.

I think this problem is actually fixed in master, by moving the data files within the Python package itself.  However, we need to document that 0.9.3 is a broken tag.

Full trace:

```
INFO:core.py:73:runcmd: RUNNING: newexp-desi --flavor dark --nspec 5 --night 20160505 --expid 2
INFO:io.py:459:read_basis_templates: Reading /project/projectdirs/desi/spectro/templates/basis_templates/v2.0/star_templates_v
2.0.fits
INFO:io.py:459:read_basis_templates: Reading /project/projectdirs/desi/spectro/templates/basis_templates/v2.0/elg_templates_v2
.0.fits
ERROR:templates.py:141:__init__: Required data file /project/projectdirs/desi/users/desi/test_desiInstall/software/cori/desisi
m/0.9.3/lib/python2.7/site-packages/desisim-0.9.3-py2.7.egg/desisim/../../data/recombination_lines.ecsv not found!
Traceback (most recent call last):
  File "/project/projectdirs/desi/users/desi/test_desiInstall/software/cori/desisim/0.9.3/bin/newexp-desi", line 4, in <module
>
    __import__('pkg_resources').run_script('desisim==0.9.3', 'newexp-desi')
  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 724, in run_script

  File "build/bdist.linux-x86_64/egg/pkg_resources/__init__.py", line 1650, in run_script

  File "/global/project/projectdirs/desi/users/desi/test_desiInstall/software/cori/desisim/0.9.3/lib/python2.7/site-packages/d
esisim-0.9.3-py2.7.egg/EGG-INFO/scripts/newexp-desi", line 98, in <module>
    seed=opts.seed)
  File "/project/projectdirs/desi/users/desi/test_desiInstall/software/cori/desisim/0.9.3/lib/python2.7/site-packages/desisim-
0.9.3-py2.7.egg/desisim/obs.py", line 118, in new_exposure
    fibermap, truth = get_targets_parallel(nspec, flavor, tileid=tileid, seed=seed)
  File "/project/projectdirs/desi/users/desi/test_desiInstall/software/cori/desisim/0.9.3/lib/python2.7/site-packages/desisim-
0.9.3-py2.7.egg/desisim/targets.py", line 142, in get_targets_parallel
    return get_targets(nspec, flavor, tileid, seed=seed)
  File "/project/projectdirs/desi/users/desi/test_desiInstall/software/cori/desisim/0.9.3/lib/python2.7/site-packages/desisim-
0.9.3-py2.7.egg/desisim/targets.py", line 231, in get_targets
    simflux, wave1, meta = elg.make_templates(nmodel=nobj, seed=seed)
  File "/project/projectdirs/desi/users/desi/test_desiInstall/software/cori/desisim/0.9.3/lib/python2.7/site-packages/desisim-
0.9.3-py2.7.egg/desisim/templates.py", line 423, in make_templates
    EM = EMSpectrum(log10wave=np.log10(self.basewave))
  File "/project/projectdirs/desi/users/desi/test_desiInstall/software/cori/desisim/0.9.3/lib/python2.7/site-packages/desisim-
0.9.3-py2.7.egg/desisim/templates.py", line 142, in __init__
    raise IOError
IOError
  Outputs
    /global/cscratch1/sd/desi/desi/spectro/sim/dailytest/20160505/fibermap-00000002.fits
    /global/cscratch1/sd/desi/desi/spectro/sim/dailytest/20160505/simspec-00000002.fits
```

**Comment by weaverba137** [comment]
The answer to this question is simply to create a new tag.  Please speak up if there is any reason not to do this now!

**Comment by moustakas** [comment]
I'm about to submit a very simple PR with some template updates.  If you could wait for that merge before tagging that'd be great!

**Comment by moustakas** [comment]
Feel free to tag desisim and close this issue, @weaverba137.

**Comment by weaverba137** [comment]
OK, I'll do that soon.  Should we do 0.9.4, or 0.10.0, or 1.0.0?

**Comment by sbailey** [comment]
Even if it violates pure semantic versioning, let's avoid going to 1.0.0 until we have reached a greater level of features and stability.  0.10.0 is good.
