### ISSUE TITLE
Obscure crash when attempting to run pixsim-desi on laptop

### ISSUE THREAD

**Issue by weaverba137** [desihub/desisim#130]
I'm trying to run a full integration test on my laptop.  newexp-desi seems to work fine, but the next command,
```
pixsim-desi --nspec 5 --night 20160524 --expid 0
```
crashes with the output below.  The error message reported with the `ValueError` is actually thrown by the cfitsio C library.

Maybe this crash isn't obscure; I've just never seen it in any integration test I've run.

* python/2.7.11
* astropy/1.1.1
* numpy/1.11.1
* desisim, desispec, specter, ... all on up-to-date master

```
Traceback (most recent call last):
  File "/Users/weaver/Documents/Code/git/desihub/desisim/bin/pixsim-desi", line 84, in <module>
    cosmics=opts.cosmics, wavemin=opts.wavemin, wavemax=opts.wavemax)
  File "/Users/weaver/Documents/Code/git/desihub/desisim/py/desisim/pixsim.py", line 169, in simulate
    desispec.io.write_image(pixfile, image)
  File "/Users/weaver/Documents/Code/git/desihub/desispec/py/desispec/io/image.py", line 43, in write_image
    hx.writeto(outfile, clobber=True)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/hdu/hdulist.py", line 689, in writeto
    hdu._prewriteto(checksum=checksum)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/hdu/compressed.py", line 1815, in _prewriteto
    self._update_compressed_data()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/astropy/io/fits/hdu/compressed.py", line 1679, in _update_compressed_data
    heapsize, self.compressed_data = compression.compress_hdu(self)
ValueError: Specified column number is out of range: 2
```

**Comment by sbailey** [comment]
I have not seen that error before.  The daily cronjob integration tests using latest master are not failing using
  * python/2.7.11 (same)
  * astropy/1.1.1 (same)
  * numpy/1.10.4 (different!)

Can you try downgrading your numpy and rerunning?

**Comment by weaverba137** [comment]
I ran the test with numpy 1.10.4, and sure enough, no such error.  So the answer is: pin to numpy/1.10.

**Comment by sbailey** [comment]
Do the desispec unit tests pass when using numpy 1.11.1?  They cover the case of writing an image to disk including photons, ivar, and compressed mask.  It looks like they don't cover the case of photons, ivar, compressed mask, followed by a readnoise image.  The unit tests may not be writing large enough images to trigger the tiling during compression.

If you can turn this into a bug report for astropy, please do so — pinning to numpy/1.10 is at best a temporary solution.
