### ISSUE TITLE
quickbrick does not run

### ISSUE THREAD

**Issue by dkirkby** [desihub/desisim#162]
The following command fails in the master branch:
```
quickbrick -b test1 --objtype ELG -n 1
```
The output (under python 2.7) is:
```
INFO:io.py:612:read_basis_templates: Reading /Data/DESI/basis_templates/v2.1/elg_templates_v2.0.fits
Traceback (most recent call last):
  File "/Users/david/anaconda/bin/quickbrick", line 6, in <module>
    exec(compile(open(__file__).read(), __file__, 'exec'))
  File "/Users/david/Cosmo/DESI/code/desisim/bin/quickbrick", line 16, in <module>
    quickbrick.main(args)
  File "/Users/david/Cosmo/DESI/code/desisim/py/desisim/scripts/quickbrick.py", line 232, in main
    meta.add_column(Column(true_objtype, dtype=(str, 10), name='OBJTYPE'))
  File "/Users/david/anaconda/lib/python2.7/site-packages/astropy/table/table.py", line 1387, in add_column
    self.add_columns([col], [index], rename_duplicate=rename_duplicate)
  File "/Users/david/anaconda/lib/python2.7/site-packages/astropy/table/table.py", line 1495, in add_columns
    self._init_from_cols(newcols)
  File "/Users/david/anaconda/lib/python2.7/site-packages/astropy/table/table.py", line 697, in _init_from_cols
    self._make_table_from_cols(self, newcols)
  File "/Users/david/anaconda/lib/python2.7/site-packages/astropy/table/table.py", line 729, in _make_table_from_cols
    raise ValueError('Duplicate column names')
ValueError: Duplicate column names
```
It looks like the code really is adding a duplicate OBJTYPE column. [According to blame](https://github.com/desihub/desisim/blame/master/py/desisim/scripts/quickbrick.py#L232) the offending line was last edited by @sbailey as part of his Py3 updates.

(This is a followup to #161 but is not related to specsim.)

**Comment by sbailey** [comment]
I'm working on quickbrick tests and fixes now.  Notes:
  1. I'm not entirely clear on the intended results for the OBJTYPE vs. TRUE_OBJTYPE columns in the case of a QSO_BAD.  Should that produce OBJTYPE='QSO_BAD' and TRUE_OBJTYPE='STAR' (or whatever other template was used to make a bad QSO)?  Or something else?  My last edit to this line was just for py2/3 string typing, but looking deeper I'm not sure I understand the surrounding logic.
  2. There appears to be yet another bug in astropy.io.fits that corrupts the truth information under python 3.5 but not 2.7.  Investigating now.  It may be another manifestation of unicode bug for which we have a workaround.

**Comment by moustakas** [comment]
```I'm not entirely clear on the intended results for the OBJTYPE vs. TRUE_OBJTYPE columns in the case of a QSO_BAD. Should that produce OBJTYPE='QSO_BAD' and TRUE_OBJTYPE='STAR' (or whatever other template was used to make a bad QSO)?```
Yes, I believe that's the desired behavior and also what is currently coded.
