### ISSUE TITLE
pixsim_mpi doesn't work with arc exposures

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#330]
`pixsim_mpi` fails on arc exposures because it tries to read a non-existent 'SKYPHOT_B/R/Z' HDU.  Plain `pixsim` does not have this problem.

Example (once you have desiconda / desisim etc. configured):
```
export DESI_SPECTRO_SIM=/global/projecta/projectdirs/desi/datachallenge/reference_runs/18.2a/spectro/sim
export DESI_SPECTRO_REDUX=/global/projecta/projectdirs/desi/datachallenge/reference_runs/18.2a/spectro/redux
export PIXPROD=mini
export SPECPROD=mini
export DESI_SPECTRO_DATA=$DESI_SPECTRO_SIM/$PIXPROD

srun -n 32 pixsim_mpi --mpi_camera 32 --night 20200315 --expid 3 --cameras b1 \
    --nspec 2 --wavemin 3600 --wavemax 3700 \
    --rawfile desi-blat.fits.fz --simpixfile simpix-blat.fits

INFO:pixsim.py:196:main: Starting pixsim at Fri Mar  2 13:37:13 2018
Traceback (most recent call last):
  File "/global/cscratch1/sd/sjbailey/desi/code/desisim/bin/pixsim_mpi", line 17, in <module>
    sys.exit(pixsim.main(args, comm=comm))
  File "/global/cscratch1/sd/sjbailey/desi/code/desisim/py/desisim/scripts/pixsim.py", line 337, in main
    spectrographs=group_spectro)
  File "/global/cscratch1/sd/sjbailey/desi/code/desisim/py/desisim/io.py", line 419, in read_simspec_mpi
    sky_hdata=native_endian(hdus[hname].data.copy().astype('f8'))
  File "/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 314, in __getitem__
    self._positive_index_of(key))
  File "/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 702, in _positive_index_of
    index = self.index_of(key)
  File "/global/common/software/desi/cori/desiconda/20180130-1.2.4-spec/conda/lib/python3.6/site-packages/astropy/io/fits/hdu/hdulist.py", line 683, in index_of
    raise KeyError('Extension {} not found.'.format(repr(key)))
KeyError: "Extension 'SKYPHOT_B' not found."
```

**Comment by sbailey** [comment]
fixed in PR #332.
