### ISSUE TITLE
tests still require old template env variables

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#35]
@moustakas : the desisim tests still require old $DESI_ELG_TEMPLATES etc environment variables.  I'm not sure if this is because some corner of the code still needs them, or if just the tests themselves need to be updated.  Can you look into this and fix the code and/or tests to use the new $DESI_BASIS_TEMPLATES system and get our tests back to a working state?

```
python setup.py test
...
======================================================================
ERROR: test_read_templates (desisim.test.test_io.TestIO)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./py/desisim/test/test_io.py", line 119, in test_read_templates
    flux, meta = io.read_templates(wave, objtype, nspec=3)
  File "./py/desisim/io.py", line 439, in read_templates
    raise ValueError("ERROR: $"+key+" not set; can't find "+objtype+" templates")
ValueError: ERROR: $DESI_ELG_TEMPLATES not set; can't find ELG templates

----------------------------------------------------------------------
```

**Comment by moustakas** [comment]
Fixed in PR #36
