### ISSUE TITLE
Latest version of quickquasars is broken

### ISSUE THREAD

**Issue by andreufont** [desihub/desisim#422]
Hi @moustakas , @alxogm - I just ran quickquasars on v2.0, using the same configuration that I used before for london/v2.0/quick-2.0, but several pixels crashed with messages similar to the one below.

It seems related to the recent changes in how the filters are being used.

multiprocessing.pool.RemoteTraceback:
"""
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desisim/master/py/desisim/scripts/quickquasars.py", line 542, in _func
    return simulate_one_healpix(**arg)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desisim/master/py/desisim/scripts/quickquasars.py", line 447, in simulate_one_healpix
    bbflux[band][these] = np.ma.getdata(1e9 * maggies[filt]) # nanomaggies
ValueError: NumPy boolean array indexing assignment cannot assign 888 input values to the 23 output values where the mask is true
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desisim/master/bin/quickquasars", line 9, in <module>
    sys.exit(main())
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/code/desisim/master/py/desisim/scripts/quickquasars.py", line 625, in main
    pool.map(_func, func_args)
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/multiprocessing/pool.py", line 266, in map
    return self._map_async(func, iterable, mapstar, chunksize).get()
  File "/global/common/software/desi/cori/desiconda/20180709-1.2.6-spec/conda/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
ValueError: NumPy boolean array indexing assignment cannot assign 888 input values to the 23 output values where the mask is true
srun: error: nid00577: task 0: Exited with exit code 1
srun: Terminating job step 14992923.11

**Comment by moustakas** [comment]
I broke it, I'll fix it!  Can you send me the exact call to quickquasars and/or healpixel or is it wrapped in a slurm script?  If the latter, can you figure out which pixel crashed so I can reproduce the issue?

**Comment by andreufont** [comment]
This reproduces the error:

#!/bin/bash

downsampling=0.40
idir=/project/projectdirs/desi/mocks/lya_forest/london/v2.0/
outdir=/project/projectdirs/desi/mocks/lya_forest/london/v2.0/tests/test-3.0/

if [ ! -d $outdir ] ; then
    mkdir -p $outdir
fi    
if [ ! -d $outdir/logs ] ; then
    mkdir -p $outdir/logs
fi
if [ ! -d $outdir/spectra-16 ] ; then
    mkdir -p $outdir/spectra-16
fi

#file=/project/projectdirs/desi/mocks/lya_forest/london/v2.0/0/0/transmission-16-0.fits
file=/project/projectdirs/desi/mocks/lya_forest/london/v2.0//1/137/transmission-16-137.fits

quickquasars --exptime 4000. -i $file --zmin 1.8 --outdir $outdir/spectra-16 --downsampling $downsampling --zbest --mags --desi-footprint --seed 123

**Comment by moustakas** [comment]
At the risk of getting (politely) yelled at for violating our software development standards, this was a 10-character fix/bug, which I decided to just push to master.  @andreufont can you `git pull` and test?

**Comment by andreufont** [comment]
hehehehe. Thanks for fixing it so quickly!

Unfortunately, I don't have the code setup at Cori, I just use the DESI environment from conda that is only updated once a day or so, so I'll have to wait before testing. 

Alternatively, would it be possible for you to run this script?
/project/projectdirs/desi/mocks/lya_forest/london/v2.0/quick-3.0/run/quickquasar_slurm_script.sh

**Comment by moustakas** [comment]
Yup, outputs are appearing in `/project/projectdirs/desi/mocks/lya_forest/london/v2.0/quick-3.0/spectra-16/`.

Please reopen this issue if any other issues become an issue.

**Comment by andreufont** [comment]
Great, it finished properly. Thanks!
