### ISSUE TITLE
Card is too long, comment will be truncated

### ISSUE THREAD

**Issue by londumas** [desihub/desisim#469]
Sending the following command
`quickquasars -i /project/projectdirs/desi/mocks/lya_forest/london/v6.0/v6.0.0/1/137/transmission-16-137.fits --outdir /project/projectdirs/desi/mocks/lya_forest/london/v6.0/v6.0.0/eboss-0.0/test-0-0/spectra-16 --zbest --bbflux --eboss --seed 123 --shift_kms_los -100.0 --gamma_kms_zfit 400.0 --zmin 1.8 --metals LYB --overwrite  --nmax 1`,
I get the following warning message, that basicaly says that some comments are too long in fits files. It might be worth correcting that:
```
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
WARNING: VerifyWarning: Card is too long, comment will be truncated. [astropy.io.fits.card]
```

**Comment by moustakas** [comment]
I tested this issue with an updated location for the mock and I don't see the warning reported, so I'm planning to close this. However, the call to `quickquasars` did crash with a different error. I leave it up to @andreufont and/or @alxogm to open a new ticket if the crash is on the critical path for other work

```
quickquasars -i /global/cfs/cdirs/desi/mocks/lya_forest/london/v9.0/v9.0.99/1/137/transmission-16-137.fits.gz --outdir /project/projectdirs/desi/mocks/lya_forest/london/v6.0/v6.0.0/eboss-0.0/test-0-0/spectra-16 --zbest --bbflux --eboss --seed 123 --shift_kms_los -100.0 --gamma_kms_zfit 400.0 --zmin 1.8 --metals LYB --overwrite --nmax 1
INFO:quickquasars.py:873:main: Load SIMQSO model
WARNING:templates.py:2363:__init__: Using modified simqso.sqmodel defined in desisim.scripts.lya_simqso_model
INFO:quickquasars.py:882:main: Load DeCAM and WISE filters for target selection sim.
in eboss_footprint constructor, nside 16
in read_sdss_footprint from file /global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/data/eboss_footprint_nside_16.txt
got data from file
In eboss_footprint constructor, dz = 0.04
in read_sdss_redshift_distribution from file /global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/data/eboss_redshift_distributon_fraction_dz_004_nside_16.txt
got data from file
ifilename /global/cfs/cdirs/desi/mocks/lya_forest/london/v9.0/v9.0.99/1/137/transmission-16-137.fits.gz
INFO:quickquasars.py:220:get_healpix_info: healpix=HPXPIXEL=137
INFO:quickquasars.py:225:get_healpix_info: nside=HPXNSIDE=16
INFO:quickquasars.py:233:get_healpix_info: hpxnest from HPXNEST = True
INFO:quickquasars.py:316:simulate_one_healpix: Read skewers in /global/cfs/cdirs/desi/mocks/lya_forest/london/v9.0/v9.0.99/1/137/transmission-16-137.fits.gz, random seed = 19270028
INFO:quickquasars.py:320:simulate_one_healpix: Read transmission file /global/cfs/cdirs/desi/mocks/lya_forest/london/v9.0/v9.0.99/1/137/transmission-16-137.fits.gz
INFO:quickquasars.py:325:simulate_one_healpix: Add FOG to redshift with sigma 150 to quasar redshift
INFO:quickquasars.py:342:simulate_one_healpix: Select QSOs in BOSS+eBOSS redshift distribution 2400 -> 1854
39.3932 <density< 39.3932
0.2853287 <fraction< 0.2853287
527 selected out of 1854
INFO:quickquasars.py:357:simulate_one_healpix: Select QSOs in BOSS+eBOSS footprint 1854 -> 527
INFO:quickquasars.py:394:simulate_one_healpix: Limit number of QSOs from 527 to nmax=1 (random subsample)
INFO:quickquasars.py:481:simulate_one_healpix: Increase wavelength range from 3470:6499 to 3329:6499 to compute magnitudes
INFO:quickquasars.py:491:simulate_one_healpix: Increase wavelength range from 3329:6499 to 3329:55501 to compute magnitudes
INFO:quickquasars.py:512:simulate_one_healpix: Simulate 1 QSOs with SIMQSO templates
INFO:quickquasars.py:546:simulate_one_healpix: Resample to transmission wavelength grid
INFO:quickquasars.py:600:simulate_one_healpix: Apply transmitted flux fraction
INFO:quickquasars.py:617:simulate_one_healpix: Apply metals: LYB
INFO:quickquasars.py:632:simulate_one_healpix: Compute QSO magnitudes
INFO:quickquasars.py:668:simulate_one_healpix: Resample to a linear wavelength grid (needed by DESI sim.)
INFO:quickquasars.py:675:simulate_one_healpix: Simulate DESI observation and write output file
INFO:quickspectra.py:64:sim_spectra: Starting simulation of 1 spectra
INFO:iers.py:82:freeze_iers: Freezing IERS table used by astropy time, coordinates.
DEBUG:simexp.py:418:simulate_spectra: loading specsim desi config eboss
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/bin/quickquasars", line 9, in <module>
    sys.exit(main())
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/scripts/quickquasars.py", line 936, in main
    simulate_one_healpix(ifilename,args,model,obsconditions,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/scripts/quickquasars.py", line 726, in simulate_one_healpix
    resolution=sim_spectra(qso_wave,qso_flux, args.program, obsconditions=obsconditions,spectra_filename=ofilename,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/scripts/quickspectra.py", line 185, in sim_spectra
    sim = desisim.simexp.simulate_spectra(wave, flux, fibermap=frame_fibermap,
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/simexp.py", line 419, in simulate_spectra
    config = _specsim_config_for_wave(wave.to('Angstrom').value, dwave_out=dwave_out, specsim_config_file=specsim_config_file)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/simexp.py", line 615, in _specsim_config_for_wave
    config = specsim.config.load_config(specsim_config_file)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/specsim/master/specsim/config.py", line 692, in load_config
    raise ValueError('No such config file "{0}".'.format(file_name))
ValueError: No such config file "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/specsim/master/specsim/data/config/eboss.yaml".
```

**Comment by andreufont** [comment]
I think this is ok, this is an old issue related to a project (eBOSS) that has already finished. We can reopen it if we need later on.
