### ISSUE TITLE
Filter transmissions should not be in speclite

### ISSUE THREAD

**Issue by julienguy** [desihub/desisim#480]
I have tried to  simulate an ELG spectrum. 
```
from desisim.templates import ELG
elg_template = ELG()
```
Because I have not the latest version of speclite, I got the following error:
```
Traceback (most recent call last):
  File "./mcefficiency.py", line 6, in <module>
    elg_template = ELG()
  File "/home/guy/software/DESI/desisim/py/desisim/templates.py", line 965, in __init__
    add_SNeIa=add_SNeIa, include_mgii=include_mgii)
  File "/home/guy/software/DESI/desisim/py/desisim/templates.py", line 453, in __init__
    self.normfilt_north = filters.load_filters(self.normfilter_north)
  File "/home/guy/software/DESI/anaconda3/lib/python3.6/site-packages/speclite/filters.py", line 1835, in load_filters
    responses.append(load_filter(name))
  File "/home/guy/software/DESI/anaconda3/lib/python3.6/site-packages/speclite/filters.py", line 1909, in load_filter
    .format(valid.group(1), filter_group_names))
ValueError: No such group 'BASS'. Choose one of ['sdss2010', 'decam2014', 'wise2010', 'hsc2017', 'lsst2016', 'bessell'].
```

Pass band filter curves of the DESI imaging surveys, which are important calibration data, should not be stored in speclite which is not a package of DESI. The filter transmission curves used for the interpretation of the DESI imaging should be saved in an environment that belongs to the DESI collaboration,  like the DESIMODEL svn.

**Comment by moustakas** [comment]
`speclite` was moved into the `desihub` organization, so I'm going to close this ticket.
