### ISSUE TITLE
fix numpy 1.17 test failures

### ISSUE THREAD

**Issue by sbailey** [desihub/desisim#506]
When testing against numpy 1.17, we get the following new failures:
```
======================================================================
ERROR: test_insert_dla (desisim.test.test_lya.TestLya)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/desihub/desisim/py/desisim/test/test_lya.py", line 65, in test_insert_dla
    self.assertGreater(len(dla_meta), 0)
TypeError: object of type 'NoneType' has no len()
```
and
```
======================================================================
FAIL: test_random_seed (desisim.test.test_templates.TestTemplates)
Test that random seed works to get the same results back
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/desihub/desisim/py/desisim/test/test_templates.py", line 74, in test_random_seed
    self.assertTrue(np.any(flux1!=flux3))
AssertionError: False is not true
```
Figure out why and fix.

**Comment by moustakas** [comment]
Current set of tests all pass, so this ticket is obsolete.
