### ISSUE TITLE
several quickgen unit tests are failing

### ISSUE THREAD

**Issue by moustakas** [desihub/desisim#558]
Running
```
python py/desisim/test/test_quickgen.py
```
fails gloriously in many places. I know this is legacy code but then we should either deprecate the code or the unit tests.

Here's one Traceback:
```
INFO:io.py:971:read_basis_templates: Reading /Users/ioannis/work/desi/spectro/templates/basis_templates/v3.2/elg_templates_v2.2.fits
DEBUG:simexp.py:418:simulate_spectra: loading specsim desi config desi
DEBUG:simexp.py:422:simulate_spectra: creating specsim desi simulator
INFO:simexp.py:444:simulate_spectra: MJD not in obsconditions, using DATE-OBS 2009-06-18T12:00:00.000
DEBUG:simexp.py:448:simulate_spectra: obsconditions SEEING = 1.1
DEBUG:simexp.py:448:simulate_spectra: obsconditions EXPTIME = 1000
DEBUG:simexp.py:448:simulate_spectra: obsconditions AIRMASS = 1.0
DEBUG:simexp.py:448:simulate_spectra: obsconditions MOONFRAC = 0.0
DEBUG:simexp.py:448:simulate_spectra: obsconditions MOONALT = -60
DEBUG:simexp.py:448:simulate_spectra: obsconditions MOONSEP = 180
DEBUG:simexp.py:490:simulate_spectra: running simulation with fastsim fiber loss method
DEBUG:simexp.py:496:simulate_spectra: source types: 1 elg
WARNING:simexp.py:511:simulate_spectra: the half light radii are fixed here for LRGs and ELGs (and not magnitude or redshift dependent)
INFO:io.py:165:write_simspec: DATE-OBS 2015-01-05T22:00:00 UTC
INFO:io.py:272:write_simspec: Wrote /Users/ioannis/desi_test_io/spectro/sim/test-quickgen/20150105/00000102/simspec-00000102.fits
INFO:fibermap.py:261:write_fibermap: iotime 0.076 sec to write fibermap-00000102.fits at 2022-01-08T15:38:07.938424
INFO:obs.py:222:new_exposure: Wrote /Users/ioannis/desi_test_io/spectro/sim/test-quickgen/20150105/00000102/fibermap-00000102.fits
INFO:iers.py:82:freeze_iers: Freezing IERS table used by astropy time, coordinates.
INFO:quickgen.py:213:main: Reading fibermap file /Users/ioannis/desi_test_io/spectro/redux/test-quickgen/preproc/20150105/00000100/fibermap-00000100.fits
Traceback (most recent call last):
  File "/Users/ioannis/code/desihub/desisim/bin/quickgen", line 11, in <module>
    sys.exit(quickgen.main(args))
  File "/Users/ioannis/code/desihub/desisim/py/desisim/scripts/quickgen.py", line 214, in main
    fibermap=read_fibermap(args.fibermap)
  File "/Users/ioannis/code/desihub/desispec/py/desispec/io/fibermap.py", line 278, in read_fibermap
    fibermap, hdr = fitsio.read(filename, ext='FIBERMAP', header=True)
  File "/Users/ioannis/opt/anaconda3/envs/desi/lib/python3.8/site-packages/fitsio/fitslib.py", line 139, in read
    with FITS(filename, **kwargs) as fits:
  File "/Users/ioannis/opt/anaconda3/envs/desi/lib/python3.8/site-packages/fitsio/fitslib.py", line 520, in __init__
    self._FITS = _fitsio_wrap.FITS(filename, self.intmode, create)
OSError: FITSIO status = 104: could not open the named file
failed to find or open the following file: (ffopen)
/Users/ioannis/desi_test_io/spectro/redux/test-quickgen/preproc/20150105/0000010
0/fibermap-00000100.fits

E/Users/ioannis/opt/anaconda3/envs/desi/lib/python3.8/unittest/case.py:704: ResourceWarning: unclosed file <_io.FileIO name='/Users/ioannis/desi_test_io/spectro/sim/test-quickgen/20150105/00000100/simspec-00000100.fits' mode='rb' closefd=True>
  outcome.errors.clear()
/Users/ioannis/opt/anaconda3/envs/desi/lib/python3.8/unittest/case.py:704: ResourceWarning: unclosed file <_io.FileIO name='/Users/ioannis/desi_test_io/spectro/sim/test-quickgen/20150105/00000101/simspec-00000101.fits' mode='rb' closefd=True>
  outcome.errors.clear()
/Users/ioannis/opt/anaconda3/envs/desi/lib/python3.8/unittest/case.py:704: ResourceWarning: unclosed file <_io.FileIO name='/Users/ioannis/desi_test_io/spectro/sim/test-quickgen/20150105/00000102/simspec-00000102.fits' mode='rb' closefd=True>
  outcome.errors.clear()
INFO:simexp.py:137:simflat: Reading flat lamp spectrum from /Users/ioannis/work/desi/spectro/templates/calib/v0.4/flat-3100K-quartz-iodine.fits
INFO:io.py:165:write_simspec: DATE-OBS 2015-01-05T22:00:00 UTC
INFO:io.py:272:write_simspec: Wrote /Users/ioannis/desi_test_io/spectro/sim/test-quickgen/20150105/00000124/simspec-00000124.fits
```

**Comment by moustakas** [comment]
Fixed in #559.
