### ISSUE TITLE
Test failure at NERSC due to basis template configuration

### ISSUE THREAD

**Issue by weaverba137** [desihub/desisim#561]
Nightly tests of desisim are failing due to the following (one!) error:
```
======================================================================
ERROR: test_qso_options (desisim.test.test_templates.TestTemplates)
Test that the QSO keyword arguments work
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/test/test_templates.py", line 256, in test_qso_options
    flux, wave, meta, objmeta = QSO(wave=self.wave, balqso=True).make_templates(
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/templates.py", line 2003, in __init__
    bal = BAL()
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/bal.py", line 27, in __init__
    balflux, balwave, balmeta = read_basis_templates(objtype='BAL')
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/io.py", line 948, in read_basis_templates
    infile = find_basis_template(ltype)
  File "/global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim/master/py/desisim/io.py", line 887, in find_basis_template
    raise IOError('No {} templates found in {}'.format(objtype, objfile_wild))
OSError: No bal templates found in /global/common/software/desi/cori/desiconda/20200801-1.4.0-spec/code/desisim-testdata/master/desi/spectro/templates/basis_templates/v3.0/bal_templates_*.fits

----------------------------------------------------------------------
```
I think it needs to look at `v3.2` rather than `v3.0`, but I'm not sure where that is configured.

**Comment by moustakas** [comment]
Sorry, I'm not sure where `DESI_BASIS_TEMPLATES` is configured for the nightly integration tests, either. There's this line which *used* to point to the `v3.0` templates
  https://github.com/desihub/desisim-testdata/blob/master/setup-testdata.sh
but I updated it in https://github.com/desihub/desisim-testdata/pull/15.

Maybe @sbailey knows off-hand?

**Comment by marcelo-alvarez** [comment]
@moustakas was this fixed by https://github.com/desihub/desisim-testdata/pull/15?

**Comment by weaverba137** [comment]
@moustakas, @marcelo-alvarez did this get fixed?
